language: node_js
node_js:
    - "node"
    - "6"
    - "6.7"
    - "6.1"
    - "6.0"
    - "5.11"
    - "5.10"
    - "5"
    - "5.9"
    - "5.0"
    - "4"
    - "4.4"
    - "4.0"
script:
  - make test
notifications:
  email: false